# Generated by Django 3.2.5 on 2021-07-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
