# Generated by Django 3.2.5 on 2021-07-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
