# Generated by Django 3.2.5 on 2021-08-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20210801_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylatlong',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='companylatlong',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
