# Generated by Django 3.2.5 on 2021-08-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20210801_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
