# Generated by Django 3.2.5 on 2021-08-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(),
        ),
    ]
